language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
  - npm install -g grunt-cli
before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 10
script:
  - grunt build
after_script:
  - killall rethinkdb
